[package]
name = "solar_homekit"
version = "1.0.0"
edition = "2024"
default-run = "solar_homekit"

[dependencies]
chrono = "0.4"
env_logger = "0.11"
futures = "0.3"
hap = { path = "hap-rs" }
log = "0.4"
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tokio-modbus = "0.17"